### ISSUE TITLE
Mod online

### ISSUE THREAD

**Issue by emanuelect** [ShrekBoards/patches#1]
Could you make an online mod for the pc version of Shrek Super Slam?

**Comment by kirbyUK** [comment]
A task like this would be very difficult (though [possible](https://www.cse.unr.edu/~mharmer/thesis/mharmer_thesis.pdf)), and I have neither the technical ability nor the desire to do it.

If you would like to play the game online, I highly recommend using [Dolphin](https://dolphin-emu.org/) with a copy of the GameCube version of the game. As you can see in this repository, most patches are ported to this version as well, and they have been in the main Dolphin repositories for about a year too.
